2024-02-09 14:57:37,463 - WARNING - Not Found: /favicon.ico
2024-02-09 15:15:06,278 - WARNING - Not Found: /favicon.ico
2024-02-09 15:22:57,783 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 15:25:44,021 - WARNING - Not Found: /favicon.ico
2024-02-09 15:33:20,877 - WARNING - Not Found: /favicon.ico
2024-02-09 15:35:21,302 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\ConnectivityType.py changed, reloading.
2024-02-09 15:39:43,298 - WARNING - Not Found: /favicon.ico
2024-02-09 15:40:29,175 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\models\ConnectivityType.py changed, reloading.
2024-02-09 15:42:55,909 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\migrations\__init__.py changed, reloading.
2024-02-09 15:43:39,220 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\models\ConnectivityType.py changed, reloading.
2024-02-09 15:48:23,431 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\__init__.py changed, reloading.
2024-02-09 15:48:23,465 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\__init__.py changed, reloading.
2024-02-09 15:49:28,580 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\__init__.py changed, reloading.
2024-02-09 15:49:28,596 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\__init__.py changed, reloading.
2024-02-09 15:50:03,580 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 15:50:03,642 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 15:50:28,761 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\__init__.py changed, reloading.
2024-02-09 15:50:28,832 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\__init__.py changed, reloading.
2024-02-09 15:50:34,965 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\__init__.py changed, reloading.
2024-02-09 15:50:36,814 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\__init__.py changed, reloading.
2024-02-09 16:19:00,022 - WARNING - Not Found: /favicon.ico
2024-02-09 16:25:41,313 - WARNING - Not Found: /favicon.ico
2024-02-09 16:44:02,450 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:45:48,674 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:46:18,991 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\ConnectivityType.py changed, reloading.
2024-02-09 16:46:24,165 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\ConnectivityType.py changed, reloading.
2024-02-09 16:46:45,938 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\ConnectivityType.py changed, reloading.
2024-02-09 16:47:22,119 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\models\ConnectivityType.py changed, reloading.
2024-02-09 16:48:19,613 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:49:20,489 - WARNING - Not Found: /favicon.ico
2024-02-09 16:54:45,959 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\ConnectivityType.py changed, reloading.
2024-02-09 16:55:52,965 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:56:28,425 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:56:47,211 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:56:52,031 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:56:56,682 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\ConnectivityType.py changed, reloading.
2024-02-09 16:57:16,518 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\Device.py changed, reloading.
2024-02-09 16:57:21,207 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\Device.py changed, reloading.
2024-02-09 16:57:30,502 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\Device.py changed, reloading.
2024-02-09 16:57:38,866 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\Device.py changed, reloading.
2024-02-09 16:57:50,592 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\DeviceProvider.py changed, reloading.
2024-02-09 16:57:59,901 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\DeviceProvider.py changed, reloading.
2024-02-09 16:58:09,182 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\DeviceProvider.py changed, reloading.
2024-02-09 16:58:16,301 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\DeviceProvider.py changed, reloading.
2024-02-09 17:21:08,700 - ERROR - Internal Server Error: /rpm-service/device/
Traceback (most recent call last):
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: device.device_provider_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\Device.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\views\Device.py", line 13, in perform_create
    serializer.save(organization_id=self.request.user_data.organization_id)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\OneData\Desktop\onecare-django-1\src\common\models.py", line 39, in save
    super().save(*args, **kwargs)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 901, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 1059, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 1100, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: device.device_provider_id
2024-02-09 17:28:06,871 - ERROR - Internal Server Error: /rpm-service/device/
Traceback (most recent call last):
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: device.device_provider_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\OneData\Desktop\onecare-django-1\src\common\models.py", line 39, in save
    super().save(*args, **kwargs)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 901, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 1059, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\base.py", line 1100, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OneData\Desktop\onecare-django-1\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: device.device_provider_id
2024-02-09 17:32:16,057 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\models\Device.py changed, reloading.
2024-02-09 17:32:21,272 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\models\Device.py changed, reloading.
2024-02-09 17:32:46,564 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\models\Device.py changed, reloading.
2024-02-09 17:33:33,128 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\models\Device.py changed, reloading.
2024-02-09 17:34:09,327 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:34:15,024 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:34:28,133 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:34:32,804 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:34:37,268 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:34:44,027 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:34:49,346 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:34:54,361 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
2024-02-09 17:36:30,873 - INFO - C:\Users\OneData\Desktop\onecare-django-1\src\rpm_service\serializers\Device.py changed, reloading.
